matrix:
- name: markdown
  dictionary:
    wordlists:
    - .wordlist.txt
    output: wordlist.dic
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
      markdown_extensions:
      - markdown.extensions.extra:
  - pyspelling.filters.html:
      comments: false
      attributes:
      - alt
      ignores:
      - ':matches(code, pre)'
      - 'code'
      - 'pre'
      - 'blockquote'
  sources:
  - 'docs/**/*.md'
  - 'README.md'
  - !'docs/songs/19_het_leven_is_een_vuile_kolerelijer.md'
  - !'docs/songs/66_ljum.md'
  default_encoding: utf-8
