#!/bin/bash

mkdir booklet

# Extract text (in code tags)
for filename in `ls *.md | egrep -v "README\.md"` 
do
  sed -n '/^```/,/^```/p' $filename > booklet/$filename
done


cd booklet

# Convert all to PDF
for filename in `ls *.md` 
do
  to=`echo $filename | sed 's/\.md/.pdf/'`
  pandoc $filename -o $to
done

rm Booklet.pdf
all_pdfs=`ls *.pdf`
pdfunite $all_pdfs Booklet.pdf

cp booklet.pdf ../Booklet.pdf