#!/bin/bash

mkdir booklet

# Extract text (in code tags)
for filename in `ls *.md | egrep -v "README\.md" | egrep -v "Quartet\.md" | egrep -v "TheFanstars\.md" | egrep -v "Discography\.md" | egrep -v "Abc\.md"` 
do
  sed -n '/^```/,/^```/p' $filename > booklet/$filename
done


cd booklet

# Convert all to PDF
for filename in `ls *.md` 
do
  to=`echo $filename | sed 's/\.md/.pdf/'`
  pandoc $filename -o $to
done

all_pdfs=`ls *.pdf | egrep -v "Booklet\.pdf" | egrep -v "Book\.pdf"`
pdfunite $all_pdfs Book.pdf

# Make booklet
bookletimposer -a Book.pdf -o Booklet.pdf

cp Book.pdf ../Book.pdf
cp Booklet.pdf ../Booklet.pdf